apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cache-seeder
  description: This worker is responsible for execute seed&clean job for mapproxy redis caches wrapping mapproxy-utils package
  annotations:
    github.com/project-slug: MapColonies/cache-seeder
  tags:
    - nodejs
    - typescript
    - expressjs
    - mapproxy-utils
    - redis
    - job-manager
spec:
  type: service
  lifecycle: production
  owner: RasterTeam
  system: Ingestion
