{{- $tracing := (include "common.tracing.merged" .) | fromYaml }}
{{- $metrics := (include "common.metrics.merged" .) | fromYaml }}
{{- $configmapName := include "configmap.fullname" . }}
{{- $redis := (include "common.redis.merged" .) | fromYaml }}
{{- $serviceUrls := (include "common.serviceUrls.merged" .) | fromYaml }}

{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmapName }}
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  TELEMETRY_TRACING_ENABLED: {{ $tracing.enabled | quote }}
  {{ if $tracing.enabled }}
  TELEMETRY_TRACING_URL: {{ $tracing.url }}
  {{ end }}
  {{ if $metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: {{ $metrics.enabled | quote }}
  TELEMETRY_METRICS_URL: {{ $metrics.url }}
  {{ end }}
  npm_config_cache: /tmp/
  QUEUE_JOB_MANAGER_BASE_URL: {{ $serviceUrls.jobManager | quote}}
  QUEUE_HEART_BEAT_MANAGER_BASE_URL: {{ $serviceUrls.heartbeatManager | quote}}
  QUEUE_HEART_BEAT_INTERVAL_MS: {{ .Values.env.queue.heartbeat.heartbeatIntervalMs | quote}}
  QUEUE_DEQUEUE_INTERVAL_MS: {{ .Values.env.queue.dequeueIntervalMs | quote}}
  QUEUE_JOB_TYPE: {{ .Values.env.queue.jobType | quote}}
  QUEUE_TASK_TYPE: {{ .Values.env.queue.tilesTaskType | quote}}
  MAPPROXY_API_URL: {{ $serviceUrls.mapproxyApi | quote}}
  SEED_ATTEMPTS: {{ .Values.env.seedAttempts | quote}}
  SEED_CONCURRENCY: {{ .Values.env.seedConcurrency | quote}}
  {{ if $redis.auth.enableRedisUser }}
  REDIS_PASSWORD: {{ $redis.auth.password | quote}}
  REDIS_USERNAME: {{ $redis.auth.username | quote}}
  REDIS_TLS: {{ .Values.redis.tls | quote}}
  {{ end }}
  GRACEFUL_RELOAD_MAX_SECONDS: {{ .Values.global.gracefulReloadMaxSeconds | quote }}
  GRACEFUL_BUMP_FACTOR: {{ .Values.env.gracefulBumpFactor | quote }}
  MAPPROXY_CMD_COMMAND: {{ .Values.env.mapproxyCmdCommand | quote }}
{{- end }}
