{{- $tracingUrl := include "cache-seeder.tracingUrl" . -}}
{{- $metricsUrl := include "cache-seeder.metricsUrl" . -}}
{{- $configmapName := include "configmap.fullname" . }}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmapName }}
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  npm_config_cache: /tmp/
  QUEUE_JOB_MANAGER_BASE_URL: {{ .Values.env.queue.jobManagerBaseUrl | quote}}
  QUEUE_HEART_BEAT_MANAGER_BASE_URL: {{ .Values.env.queue.heartbeat.heartbeatManagerBaseUrl | quote}}
  QUEUE_HEART_BEAT_INTERVAL_MS: {{ .Values.env.queue.heartbeat.heartbeatIntervalMs | quote}}
  QUEUE_DEQUEUE_INTERVAL_MS: {{ .Values.env.queue.dequeueIntervalMs | quote}}
  QUEUE_JOB_TYPE: {{ .Values.env.queue.jobType | quote}}
  QUEUE_TASK_TYPE: {{ .Values.env.queue.tilesTaskType | quote}}
  MAPPROXY_API_URL: {{ .Values.env.mapproxy.mapproxyApiUrl | quote}}
  SEED_ATTEMPTS: {{ .Values.env.seedAttempts | quote}}
  SEED_CONCURRENCY: {{ .Values.env.seedConcurrency | quote}}
  REDIS_PASSWORD: {{ .Values.env.redis.password | quote}}
  REDIS_USERNAME: {{ .Values.env.redis.user | quote}}
{{- end }}
