{{- $storage := (include "common.storage.merged" .) | fromYaml }}
{{- $s3 := (include "common.s3.merged" .) | fromYaml }}

{{- if and (eq (upper $storage.tilesStorageProvider) "S3") ($s3.createSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $s3.secretName }}
type: Opaque
stringData:
  accessKeyId: {{ quote $s3.accessKeyId }}
  secretAccessKey: {{ quote $s3.secretAccessKey }}
{{- end }}
